from setuptools import setup

from moloni.__version__ import __version__

setup(
    name="python-moloni",
    version=__version__,
    install_requires=["requests", "cachetools>=4.2", "pydantic"],
    extras_require={
        "aws-caching": ["aws-secretsmanager-caching", "boto3"],
        "aws": ["boto3"],
    },
    packages=[
        "moloni.api",
        "moloni.base",
        "moloni.api.bankaccounts_client",
        "moloni.api.billsoflading_client",
        "moloni.api.companies_client",
        "moloni.api.countries_client",
        "moloni.api.creditnotes_client",
        "moloni.api.currencies_client",
        "moloni.api.customeralternateaddresses_client",
        "moloni.api.customerreturnnotes_client",
        "moloni.api.customers_client",
        "moloni.api.debitnotes_client",
        "moloni.api.deductions_client",
        "moloni.api.deliverymethods_client",
        "moloni.api.deliverynotes_client",
        "moloni.api.documentmodels_client",
        "moloni.api.documents_client",
        "moloni.api.documentsets_client",
        "moloni.api.estimates_client",
        "moloni.api.fiscalzones_client",
        "moloni.api.identificationtemplates_client",
        "moloni.api.invoicereceipts_client",
        "moloni.api.invoices_client",
        "moloni.api.languages_client",
        "moloni.api.maturitydates_client",
        "moloni.api.measurementunits_client",
        "moloni.api.ownassetsmovementguides_client",
        "moloni.api.paymentmethods_client",
        "moloni.api.productcategories_client",
        "moloni.api.products_client",
        "moloni.api.receipts_client",
        "moloni.api.salesmen_client",
        "moloni.api.simplifiedinvoices_client",
        "moloni.api.subscription_client",
        "moloni.api.suppliers_client",
        "moloni.api.taxes_client",
        "moloni.api.taxexemptions_client",
        "moloni.api.users_client",
        "moloni.api.vehicles_client",
        "moloni.api.warehouses_client",
        "moloni.api.waybills_client",
        "moloni.base.MoloniBaseClient",
        "moloni.base.MoloniBaseUrl",
        "moloni.base.endpoint",
        "moloni.base.fill_query_params",
        "moloni.base.validate_data",
        "moloni.base.setup_logger",
        "moloni.base.NoMoreRecords",
        "moloni.base.ApiException",
        "moloni.base.AuthConfig",
        "moloni.base.ApiResponse",
    ],
    url="https://github.com/saleweaver/python-moloni",
    license="MIT",
    author="Michael",
    author_email="michael@datastic.co",
    description="Python wrapper for the Moloni API",
)
